[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
buildCommand = ""
startCommand = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"

[[services]]
name = "worker"
buildCommand = ""
startCommand = "celery -A src.celery worker --loglevel=info"

[[services]]
name = "beat"
buildCommand = ""
startCommand = "celery -A src.celery beat --loglevel=info"